name: Trigger .NET Build Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    uses: ./.github/workflows/dotnetbuild.yaml
    with:
      project_path: "./MyProject.sln"
      build_output: "./publish"
      artifact_name: "MyApp"
      storage_type: "NAS"
      storage_path: "E:\\Artifactory"  # Only needed if storage_type is 'NAS'
    secrets:
      GH_TOKEN: "ATBBkRBUv63b7S8SXhZ3Yj6heSNS0DCDF317"
